### PR TITLE
feat(release): add release command

### PR DESCRIPTION
**Pull request by pfongkye**
Add release workflow command to enable automatic release of a configured project.

### CODE REVIEW

**Review by greg0ire — COMMENTED** [review]
Are there any docs/README.md changes that should be made?

**Comment by pfongkye** [comment]
> Are there any docs/README.md changes that should be made?

I'll check and add a simple message as we would work on how to configure projects for release afterwards.

**Review by greg0ire — APPROVED** [review]

**Comment by greg0ire** [comment]
Thanks @pfongkye ! Should we delete the `release` branch?

**Comment by greg0ire** [comment]
Done.

**Pull request merged**
